services:
  gridsystem.api:
    image: gridsystem.api
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: GridSystem.Api/Dockerfile
